// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwiEukeKommHPfnPXBEf1DMIfZN9Xqwv8',
    appId: '1:1087296546308:android:395c62c76c8a1934d57751',
    messagingSenderId: '1087296546308',
    projectId: 'student-assistant-c75ce',
    storageBucket: 'student-assistant-c75ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV06jmAj7QCgj6-YOaDYvmMjjF5Yd9ozM',
    appId: '1:1087296546308:ios:cf644fd5418f6100d57751',
    messagingSenderId: '1087296546308',
    projectId: 'student-assistant-c75ce',
    storageBucket: 'student-assistant-c75ce.firebasestorage.app',
    iosBundleId: 'com.example.studentAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFmjkcQ9B7FdGr6yUpzSepR-pc9JwwD7I',
    appId: '1:1087296546308:web:4762483eccb78873d57751',
    messagingSenderId: '1087296546308',
    projectId: 'student-assistant-c75ce',
    authDomain: 'student-assistant-c75ce.firebaseapp.com',
    storageBucket: 'student-assistant-c75ce.firebasestorage.app',
    measurementId: 'G-80E1EYWM1N',
  );

}